<?php

/**#@+
  * Application Settings
  *
  * This section includes settings for Database connectivity, base url, email config, and more.
  * These settings are MANDATORY. If they are not configured properly OpenCAD will not function correctly.
  * When you save this file, rename it to 'oc-config.php', as it will not work as it is.
  * When editing configuration constants be sure to only edit the contents of the second set of quotes in each.
  *
  * @since 1.0a RC2
  **/

/**#@+
 * Community Name
 *
 * This is where you will change the community name to suit your Community.
 * Only change the variable named 'My Community'
 *
 * @since 1.0a RC1
 **/
define('COMMUNITY_NAME', '<COMMUNITY_NAME>');

/**#@+
 * Language Settings
 *
 * These options assert the default language and wiriting direction for the application.
 * These may be overidden by options in a users profile (Feature in a later version.)
 * 
 * @default DEFAULT_LANGUAGE 'en'
 * @default DEFAULT_LANGUAGE_DIRECTION 'ltr'
 *
 * @since 0.2.6
 **/
define('DEFAULT_LANGUAGE', 'en');
define('DEFAULT_LANGUAGE_DIRECTION', 'ltr');

/**#@+
 *
 * Database connection variables
 * These are viable to the CAD system, and must be correct.
 * DB_NAME will typically have a subdirectory, such as 'OpenCAD_(database name)'
 * DB_USER is sometimes different, it can have a subdirectory and sometimes it doesn't. An example would be 'opencad_(username)'
 * DB_PASSWORD will be your password that you created with the user. This has no subdirectory.
 * DB_HOST can vary, it can be localhost or '127.0.0.1', if these do not work then please contact our support desk.
 *
 * @since 1.0a RC1
 *
 **/
define('DB_HOST', '<DB_HOST>');
define('DB_USER', '<DB_USER>');
define('DB_PASSWORD', '<DB_PASSWORD>');
define('DB_NAME', '<DB_NAME>');
define("DB_PREFIX", '<DB_PREFIX>');

/**#@+
 * Base URL Settings
 *
 * BASE_URL - The URL to your installation of OpenCAD inlcuding,
 *             if utilized, it's subdirectory
 *
 *             Valid Examples include:
 *             //example.com - Root domain, no subdirectory
 *             //subdomain.example.com - subdomain, no subdirectory
 *             //subdomain.example.com/subdir - subdomain with subdirectory
 *             //example.com/subdir - root domain with subdirectory
 *
 *             The OpenCAD team does not recommend including the trailing / on any of the above examples.
 *             It won't necessarily break anything but just makes reference look strange having
 *             two slashed when it isn't needed.
 *
 * @since 1.0a RC1
 * 
 **/
define('BASE_URL', '<BASE_URL>');

/**#@+
  * ENABLE_API_SECURITY
  *
  * The API-Key is used to authenticate requests from logedout users,
  * it is also used in creating cookie 'aljksdz7' which stors the API-Key
  * and the session id of the loged in user.
  *
  * This setting should always be enabled.
  * 
  * @since OpenCAD version 0.2.6
  * (Imported from ATVG-CAD 1.3.0.0)
  *
  **/
  define('ENABLE_API_SECURITY', <API_SECURITY>);

/**#@+
 * To & From emails for system generated emails
 * To be used in a later version for notificaton emails
 *
 * @since 1.0a RC2
 *
 **/
define('CAD_FROM_EMAIL', '<CAD_FROM_EMAIL>');
define('CAD_FROM_NAME', COMMUNITY_NAME.' CAD');
define('CAD_TO_EMAIL', '<CAD_TO_EMAIL>');
define('CAD_TO_NAME', COMMUNITY_NAME.' Administrators');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link  OpenCAD.io secret-key service - coming soon!}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * Tese are also automatically generated by the installer during the "Core Configuration" step.
 * 
 * UTILIZIATION TO BE IMPLEMENTED
 *
 * @since 1.0a RC2
 **/
define('AUTH_KEY',         '<AUTH_KEY>');
define('SECURE_AUTH_KEY',  '<SECURE_AUTH_KEY>');
define('LOGGED_IN_KEY',    '<LOGGED_IN_KEY>');
define('NONCE_KEY',        '<NONCE_KEY>');
define('AUTH_SALT',        '<AUTH_KEY>');
define('SECURE_AUTH_SALT', '<SECURE_AUTH_SALT>');
define('LOGGED_IN_SALT',   '<LOGGED_IN_SALT>');
define('NONCE_SALT',       '<NONCE_SALT>');
define('COOKIE_NAME', '<COOKIE_NAME>');

/**#@+
  * Feature Settings
  *
  * These settings effect OpenCAD's core functions
	*
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since  OpenCAD 1804
  *
  **/

/**#@+
 * OpenCAD Feature Settings - LEO
 *
 * This section controls settings for OpenCAD's core features for LEO
 *
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD 0.2.3
 * 
 **/

 /**#@+
  * POLICE_NCIC
  *
  * Shows or hides NCIC functionality on MDT console.
  * If 'true' then LEO will be able to use NCIC functions without the need for
  * a dispatcher, else if 'false' then LEO will require the presence of
  * dispatcher to use the NCIC function.
	*
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD 1804
  *
  **/
define('POLICE_NCIC', <POLICE_NCIC>);

/**#@+
 * POLICE_CALL_SELFASSIGN
 * 
 * Enables or disables the Self Assign functionality on the MDT console for Police.
 * If 'true', then it enables the self assign function , if 'false', then the self assign function will be disabled.
 * 
 * These settings will likely be moved to a *_options table in a future version
 * 
 * since OpenCAD Version OpenCAD version 0.2.6
 * 
 **/
define('POLICE_CALL_SELFASSIGN', <POLICE_CALL_SELFASSIGN>);


/**#@+
 * OpenCAD Feature Settings - Fire
 *
 * This section controls settings for OpenCAD's core features for Fire
 *
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD version 0.2.3
 * 
 **/

 /**#@+
	* FIRE_PANIC
	*
	* Shows or hides Panic functionality on MDT console for Fire
	* If 'true' then Fire personnel will be able to use the Panic button,
	* else if 'false' then Fire personnel will not be able to use the Panic button.
	*
	* These settings will likely be moved to an *_options table in a future version.
	*
  * @since OpenCAD version 0.2.3
  *
	**/
  define('FIRE_PANIC', <FIRE_PANIC>);


 /**#@+
	* FIRE_BOLO
	*
	* Shows or Hides BOLO functionality on MDT console for Fire
	* If 'true' then Fire personnel will be able to view the BOLO board,
	* if 'false' then Fire personnel will not be able to view the BOLO board
	*.
	* These settings will likely be moved to an *_options table in a future version.
	*
  * @since OpenCAD version 0.2.3
  *
	**/
 define('FIRE_BOLO', <FIRE_BOLO>);

/**#@+
  * FIRE_NCIC_NAME
  *
  * Shows or hides NCIC name functionality on MDT console for Fire
  * If 'true' then Fire personnel will be able to use the NCIC name name lookup,
  * else if 'false' then Fire personnel will not be able to use
	* NCIC name lookup.
	*
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
 define('FIRE_NCIC_NAME', <FIRE_NCIC_PLATE>);

/**#@+
	* FIRE_NCIC_PLATE
	*
	* Shows or hides NCIC plate functionality on MDT console for Fire
	* If 'true' then Fire personnel will be able to use the NCIC plate lookup
	* function, if 'false' then Fire personnel will not be
	* able to use the NCIC plate look-up function.
	*
	* These settings will likely be moved to an *_options table in a future version.
	*
	* @since OpenCAD version 0.2.3
	**/
 define('FIRE_NCIC_PLATE', <FIRE_NCIC_PLATE>);

 /**#@+
 * FIRE_CALL_SELFASSIGN
 * 
 * Enables or disables the Self Assign functionality on the MDT console for the Fire Department.
 * If 'true', then it enables the self assign function , if 'false', then the self assign function will be disabled.
 * 
 * These settings will likely be moved to a *_options table in a future version
 * 
 * since OpenCAD Version OpenCAD version 0.2.6
 **/
define('FIRE_CALL_SELFASSIGN', <FIRE_CALL_SELFASSIGN>);

/**#@+
  * OpenCAD Feature Settings - EMS
  *
  * This section controls settings for OpenCAD's core features for EMS
	*
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/

/**#@+
	 * EMS_PANIC
	 *
	 * Shows or hides Panic functionality on MDT console for EMS
	 * If 'true' then EMS personnel will be able to use the Panic button,
	 * else if 'false' then EMS personnel will not be able to use the Panic button.
   * 
	 * These settings will likely be moved to an *_options table in a future version.
	 *
	 * @since OpenCAD version 0.2.3
	 **/
	define('EMS_PANIC', <EMS_PANIC>);

/**#@+
	 * EMS_BOLO
	 *
	 * Shows or hides BOLO functionality on MDT console for EMS
	 * If 'true' then EMS personnel will be able to view the BOLO board.
	 * else if 'false' then EMS personnel will not be able to view the BOLO board.
   *  
	 * These settings will likely be moved to an *_options table in a future version.
	 *
	 * @since OpenCAD version 0.2.3
	 **/
	define('EMS_BOLO', <EMS_BOLO>);


/**#@+
	 * EMS_NCIC_NAME
	 *
	 * Shows or hides NCIC name functionality on MDT console for EMS
	 * If 'true' then EMS personnel will be able to use the NCIC name lookup
	 * funcion, else if 'false' then EMS personnel will not be
	 * to use the NCIC name lookup function.
	 *
	 * These settings will likely be moved to an *_options table in a future version.
	 *
	 * @since OpenCAD version 0.2.3
	 **/
	define('EMS_NCIC_NAME', <EMS_NCIC_NAME>);

/**#@+
	 * EMS_NCIC_PLATE
	 *
	 * Shows or hides NCIC plate functionality on MDT console for EMS
	 * If 'true' then EMS personnel will be able to use the NCIC plate function,
	 * else if 'false' then EMS personnel will not be able to use the NCIC plate function.
   * 
	 * These settings will likely be moved to an *_options table in a future version.
	 *
	 * @since OpenCAD version 0.2.3
	 **/
	define('EMS_NCIC_PLATE', <EMS_NCIC_PLATE>);

/**#@+
 * EMS_CALL_SELFASSIGN
 * 
 * Enables or disables the Self Assign functionality on the MDT console for EMS.
 * If 'true', then it enables the self assign function , if 'false', then the self assign function will be disabled.
 * 
 * These settings will likely be moved to a *_options table in a future version
 * 
 * since OpenCAD Version OpenCAD version 0.2.6
 **/
define('EMS_CALL_SELFASSIGN', <EMS_CALL_SELFASSIGN>);


/**#@+
	 * OpenCAD Feature Settings - Roadside Assistance / Tow
	 *
	 * This section controls settings for OpenCAD's core features for Roadside Assistance
	 * These settings will likely be moved to an *_options table in a future version.
	 *
	 * @since OpenCAD version 0.2.3
	 **/

/**#@+
 * ROADSIDE_PANIC
 *
 * Shows or hides the Panic functionality on MDT console for Roadside Assistance
 * If 'true' then Roadside Assistance Operator will be able to use the Panic button,
 * else if 'false' then the roadside assistance operator will not be able to use the Panic button.
 * 
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD version 0.2.3
 **/
define('ROADSIDE_PANIC', <ROADSIDE_PANIC>);

/**#@+
 * ROADSIDE_BOLO
 *
 * Shows or hides the BOLO functionality on MDT console for Roadside Assistance
 * If 'true' then a Roadside Assitance Operator will be able to use the BOLO function,
 * if 'false' then the Roadside Assistance Operator will not be able to use the BOLO function.
 * 
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD version 0.2.3
 **/
define('ROADSIDE_BOLO', <ROADSIDE_BOLO>);

/**#@+
 * ROADSIDE_NCIC_NAME
 *
 * Shows or hides NCIC Name functionality on MDT console for Roadside Assistance
 * If 'true' then the Roadside Assistance Operator will be able to use NCIC name query without the need for
 * a dispatcher, if 'false' then the Roadside Assistance Operator will require the presence of
 * dispatcher to use NCIC name query functions.
 * 
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD version 0.2.3
 **/
define('ROADSIDE_NCIC_NAME', <ROADSIDE_NCIC_NAME>);

/**#@+
 * ROADSIDE_NCIC_PLATE
 *
 * Shows or hides NCIC Plate functionality on MDT console for Roadside Assistance
 * If 'true' then Roadside Assistance Operators will be able to use NCIC plate query without the need for
 * a dispatcher, else if 'false' then the Roadside Assistance Operators will require the presence of
 * dispatcher to use NCIC plate query funcationality.
 * 
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD version 0.2.3
 **/
define('ROADSIDE_NCIC_PLATE', <ROADSIDE_NCIC_PLATE>);

/**#@+
 * ROADSIDE_CALL_SELFASSIGN
 * 
 * Enables or disables the Self Assign functionality on the MDT console for Roadside Assistance.
 * If 'true', then it enables the self assign function , if 'false', then the self assign function will be disabled.
 * 
 * These settings will likely be moved to a *_options table in a future version
 * 
 * since OpenCAD Version OpenCAD version 0.2.6
 **/
define('ROADSIDE_CALL_SELFASSIGN', <ROADSIDE_CALL_SELFASSIGN>);

/**#@+
 * OpenCAD Feature Settings - Civilian
 *
 * This section controls settings for OpenCAD's core features for Civilian.
 *
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD 0.2.4
 **/

/**#@+
 * CIV_WARRANT
 *
 * Allow/Disallow Civilians from managing their warrants. If set to 'true'
 * then Civs will be able to delete warrants from their profile, else if set
 * to 'false' then Civs will not have the ability to remove warrants.
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD 1803
 **/
define('CIV_WARRANT', <CIV_WARRANT>);

/**#@+
 * CIV_REG
 *
 * Allow/Disallow direct registration for Civillians.
 * If set to 'true' then civillians will not require admin approval, esle if
 * set to 'false' then Civillian registartion will require Admin approval.
 * Allow/Disallow immediate regitration for civilians.
 * If 'true' then civilian registartion will require Administrator approval
 * else if 'false' then civilian registrations will NOT require
 * Administrator approval.
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD 1803
 **/
define('CIV_REG', <CIV_REG>);

/**#@+
 * CIV_LIMIT_MAX_IDENTITIES default mode '0'
 *
 * Toggle limiting maximum number of civilian identities
 * If CIV_LIMIT_MAX is '0' then civilian will be able to create unlimited identites.
 * Otherwise, if CIV_LIMIT_MAX is a value other than '0' then it will cap the maximum
 * number of possible identites to that value
 *  
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD OpenCAD version 0.2.6
 * @from ATVG-CAD 1.3.2.0
 **/
define('CIV_LIMIT_MAX_IDENTITIES', '<CIV_LIMIT_MAX_IDENTITIES>');

/**#@+
  * CIV_LIMIT_MAX_VEHICLES
 * 
 * CIV_LIMIT_MAX_VEHICLES default mode '0'
 *
 * Toggle limiting maximum number of civilian vehicles
 * If CIV_LIMIT_MAX_VEHICLES is '0' then civilian will be able to create unlimited vehicles.
 * Otherwise, if CIV_LIMIT_MAX_VEHICLES is a value other than '0' then it will cap the maximum
 * number of possible vehicles to that value
 *  
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD OpenCAD version 0.2.6
 * @from ATVG-CAD 1.3.2.0
 **/
define('CIV_LIMIT_MAX_VEHICLES', '<CIV_LIMIT_MAX_VEHICLES>');

/**#@+
  * CIV_LIMIT_MAX_WEAPONS
 * 
 * CIV_LIMIT_MAX_WEAPONS default mode '0'
 *
 * Toggle limiting maximum number of civilian weapons
 * If CIV_LIMIT_MAX_WEAPONS is '0' then civilian will be able to create unlimited weapons.
 * Otherwise, if CIV_LIMIT_MAX_WEAPONS is a value other than '0' then it will cap the maximum
 * number of possible weapons to that value
 *  
 * These settings will likely be moved to an *_options table in a future version.
 *
 * @since OpenCAD OpenCAD version 0.2.6
 * @from ATVG-CAD 1.3.2.0
 **/
define('CIV_LIMIT_MAX_WEAPONS', '<CIV_LIMIT_MAX_WEAPONS>');

/**#@+
  * Administrative Settings
	*
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since  OpenCAD 0.2.3
  **/

/**#@+
  * MODERATOR_APPROVE_USER
  *
  * If 'true' then Moderators will be able to approve new user requests
  * else, if 'false' then Moderators will not be able to approve new
  * user requests.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_APPROVE_USER', <MODERATOR_APPROVE_USER>);

/**#@+
  * MODERATOR_EDIT_USER
  *
  * If 'true' then Moderators will be able to edit users profile,
  * if 'false' then Moderators will not be able to edit users profile.
  * This includes name, email, identifier, and roles. Moderators will
  * be able to add user groups but the removal of them is governed
  * by the MODERATOR_REMOVE_GROUPS setting.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_EDIT_USER', <MODERATOR_EDIT_USER>);

/**#@+
  * MODERATOR_SUSPEND_WITH_REASON
  *
  * If 'true' then Moderators will be able Suspend users with a reason,
  * if 'false' Moderators will not be able suspend users wth a reason.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_SUSPEND_WITH_REASON', <MODERATOR_SUSPEND_WITH_REASON>);

/**#@+
  * MODERATOR_SUSPEND_WITHOUT_REASON
  *
  * If 'true' then Moderators will be able suspend users without a reason,
  * if 'false' Moderators will not be able suspend users without a reason.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_SUSPEND_WITHOUT_REASON', <MODERATOR_SUSPEND_WITHOUT_REASON>);

/**#@+
  * MODERATOR_REACTIVATE_USER
  *
  * If 'true' then Moderators will be able to ractvate users else,
  * if 'false' Moderators will not be able to reactivate users.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_REACTIVATE_USER', <MODERATOR_REACTIVATE_USER>);

/**#@+
  * MODERATOR_REMOVE_GROUP
  *
  * If 'true' then Moderators will be able to remove user's groups else,
  * if 'false' Moderators will not be able to remove user's groups.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_REMOVE_GROUP', <MODERATOR_REMOVE_GROUP>);

/**#@+
  * MODERATOR_DELETE_USER
  *
  * If 'true' then Moderators will be able to delete users,
  * if 'false' Moderators will not be able to delete users.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_DELETE_USER', <MODERATOR_DELETE_USER>);

/**#@+
  * MODERATOR_NCIC_EDITOR
  *
  * If 'true' then Moderators will be able to access the NCIC editor,
  * if 'false' Moderators will not be able to access the NCCIC editor.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('MODERATOR_NCIC_EDITOR', <MODERATOR_NCIC_EDITOR>);

/**#@+
  * MODERATOR_DATA_MANAGER
  *
  * If 'true' then Moderators will be able to access the Game Data Manager,
  * else if 'false' then Moderators will not be able to access the Gam Data Manager.
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version OpenCAD version 0.2.6
  **/
  define('MODERATOR_DATA_MANAGER', <MODERATOR_DATA_MANAGER>);

/**#@+
  * MODERATOR_DATAMAN_CITATIONTYPES
  * If 'true' then Moderators will have access to the Citation Types Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_CITATIONTYPES', <MODERATOR_DATAMAN_CITATIONTYPES>);

/**#@+
  * MODERATOR_DATAMAN_DEPARTMENTS
  * If 'true' then Moderators will have access to the Departments Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_DEPARTMENTS', <MODERATOR_DATAMAN_DEPARTMENTS>);

/**#@+
  * MODERATOR_DATAMAN_INCIDENTTYPES
  * If 'true' then Moderators will have access to the Incident Types Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_INCIDENTTYPES', <MODERATOR_DATAMAN_INCIDENTTYPES>);

/**#@+
  * MODERATOR_DATAMAN_RADIOCODES
  * If 'true' then Moderators will have access to the Radio Codes Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_RADIOCODES', <MODERATOR_DATAMAN_RADIOCODES>);

/**#@+
  * MODERATOR_DATAMAN_STREETS
  * If 'true' then Moderators will have access to the Streets Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_STREETS', <MODERATOR_DATAMAN_STREETS>);

/**#@+
  * MODERATOR_DATAMAN_VEHICLES
  * If 'true' then Moderators will have access to the Vehiciels Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_VEHICLES', <MODERATOR_DATAMAN_VEHICLES>);

/**#@+
  * MODERATOR_DATAMAN_WARNINGTYPES
  * If 'true' then Moderators will have access to the Warning Types Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_WARNINGTYPES', <MODERATOR_DATAMAN_WARNINGTYPES>);

/**#@+
  * MODERATOR_DATAMAN_WARRANTTYPES
  * If 'true' then Moderators will have access to the Warrant Types Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_WARRANTTYPES', <MODERATOR_DATAMAN_WARRANTTYPES>);

/**#@+
  * MODERATOR_DATAMAN_WEAPONS
  * If 'true' then Moderators will have access to the Weapoons Manager module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_WEAPONS', <MODERATOR_DATAMAN_WEAPONS>);

/**#@+
  * MODERATOR_DATAMAN_IMPEXPRESET
   * If 'true' then Moderators will have access to the Radio Import/Export/Reset module of the Game Data Manager,
  * else if 'false' then Moderators will be denied access.
  *
  * @since OpenCAD version 0.2.6
  *
  **/
  define('MODERATOR_DATAMAN_IMPEXPRES', <MODERATOR_DATAMAN_IMPEXPRESET>);

/**#@+
  * Extra Settings
	*
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/

/**#@+
  * DEMO_MODE
  *
  * If 'true' then various user management features of OpenCAD will be
  * locked down, else if 'false' then OpenCAD's full functionality
  * will be available to use.
  *
  * it will use the default generic avatar image included with OpenCAD .
  *
  * These settings will likely be moved to an *_options table in a future version.
  *
  * @since OpenCAD version 0.2.3
  **/
define('DEMO_MODE', <DEMO_MODE>);


/**#@+
  * USE_GRAVATAR
  *
  * OpenCAD will dynamically retrieve your avatar from {@link Gravatar http://en.gravatar.com/} if you have an account. Otherwise
  * it will use the default generic avatar image included with OpenCAD .
  *
	* These settings will likely be moved to an *_options table in a future version.
	*
  * @since 1.0a RC1
  **/

define('USE_GRAVATAR', <USE_GRAVATAR>);

/**#@+
  * OC_DEBUG
  *
  * If 'true' then OpenCAD will print all session variables and display ALL PHP errors and warnings.
  * Otherwise, if 'false' then OpenCAD will not print session variables or display PHP errors and warnings
  * and respect the servers error reporting settings.
  *
  * DEFAULT VALUE: false
	*
  * @since OpenCAD OpenCAD version 0.2.6
  **/
  define('OC_DEBUG', false);

/** That's all, stop editing! Happy roleplaying. **/
/**    Absolute path to the OpenCAD directory.   **/
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

if(isset($_NOLOAD)){
  if($_NOLOAD['oc-functions'] == 'true'){}
  else{
    include ABSPATH . "oc-functions.php";
  }
}
else
  include ABSPATH . "oc-functions.php";
?>
